- rpm/rpm.go
- rpm/rpm_test.go
> fixed rpm version parse

- acceptance/deb_acceptance_test.go
- acceptance/rpm_acceptance_test.go
- acceptance/testdata/complex.386.yaml
- acceptance/testdata/deb.386.dockerfile
- acceptance/testdata/rpm.386.dockerfile
- acceptance/testdata/simple.386.yaml
- deb/deb.go
- deb/deb_test.go
- rpm/rpm.go
> fix: arch map for debian/rpm packages

- deb/deb_test.go
- glob/glob.go
- glob/glob_test.go
- rpm/rpm.go
- rpm/rpm_test.go
> chore: improving error handling and wrapping

- acceptance/testdata/complex.386.yaml
- acceptance/testdata/complex.yaml
- deb/deb_test.go
- rpm/rpm.go
- rpm/rpm_test.go
> fix: rpm: deal with dashes on version

- acceptance/acceptance_test.go
- acceptance/deb_acceptance_test.go
- acceptance/rpm_acceptance_test.go
- acceptance/testdata/deb.min.dockerfile
- acceptance/testdata/min.yaml
- acceptance/testdata/rpm.min.dockerfile
- cmd/nfpm/main.go
- nfpm.go
- nfpm_test.go
- rpm/rpm.go
> fix: better validations

- .gitignore
- Makefile
- acceptance/acceptance_test.go
- acceptance/deb_acceptance_test.go
- acceptance/rpm_acceptance_test.go
- acceptance/testdata/complex.386.yaml
- acceptance/testdata/complex.yaml
- acceptance/testdata/deb.386.complex.dockerfile
- acceptance/testdata/deb.complex.dockerfile
- acceptance/testdata/rpm.386.complex.dockerfile
- acceptance/testdata/rpm.complex.dockerfile
- deb/deb.go
- deb/deb_test.go
- nfpm.go
- rpm/rpm.go
- rpm/rpm_test.go
- rpm/testdata/spec_4.12.x.golden
- rpm/testdata/spec_4.13.x.golden
- rpm/testdata/spec_4.14.x.golden
refs https://github.com/goreleaser/goreleaser/issues/676#issuecomment-389680783
cc/ @nhinds
> feat: Create managed empty folders

- acceptance/acceptance_test.go
- deb/deb.go
- rpm/rpm.go
- rpm/rpm_test.go
ref https://github.com/goreleaser/goreleaser/issues/714
> fix: windows paths inside tar/ar files

- README.md
Signed-off-by: Daehyeok Mun <daehyeok@gmail.com>
> Fix broken link to nfpm piper on GoReleaser.

- acceptance/acceptance_test.go
- acceptance/testdata/release.rpm.dockerfile
- acceptance/testdata/release.rpm.yaml
- nfpm.go
- rpm/rpm.go
- rpm/rpm_test.go
- rpm/testdata/spec_4.15.x.golden
> fix: improve rpm release config

- CONTRIBUTING.md
- deb/deb.go
- nfpm.go
This adds support for a "rules" debian package script.
> feat: added support for "rules" debian package file

- .travis.yml
> bump: go 1.13

- go.mod
- go.sum
> bump: deps

- .travis.yml
- Makefile
- README.md
- go.mod
- go.sum
- rpm/rpm.go
> fix: remove last mentions to rpmbuild

- go.mod
- go.sum
- rpm/rpm.go
- rpm/rpm_test.go
- testdata/overrides.yaml
> fix: rpm groups

- rpm/rpm.go
resolve empty dir permission issues and re add the MTime back to the files and directories in the RPM
Closes #95
> fix(#95): resolve empty dir permission issues

- go.mod
- go.sum
- rpm/rpm.go
- rpm/rpm_test.go
refs https://github.com/google/rpmpack/pull/33
refs https://github.com/goreleaser/goreleaser/issues/1229
> fix(rpm): desc, summary and group

- go.mod
- go.sum
- rpm/rpm.go
refs https://github.com/google/rpmpack/pull/33
> fix: bump rpmpack

- cmd/nfpm/main.go
refs https://github.com/goreleaser/nfpm/pull/141#issuecomment-633282634
> feat: allow to specify the packager

- .github/workflows/build.yml
refs https://github.com/goreleaser/goreleaser/pull/1610
> chore(ci): unshallow clone

- acceptance/testdata/deb.complex.dockerfile
- acceptance/testdata/rpm.complex.dockerfile
> test: pkg dependencies

- go.mod
- go.sum
> feat: update rpmpack

- Makefile
- acceptance/acceptance_test.go
run the faster tests first, and if they pass run the acceptance tests as well...
> chore(ci): run fast tests first

- .github/workflows/gosum.yml
no need to create a PR IMHO...
> fix: auto-commit go mod tidy

- www/docs/configuration.md
refs https://gophers.slack.com/archives/C3T1JU24B/p1601624461006100
> docs: globs

- internal/sign/rsa.go
> fix: Fix hash name typo.

- go.mod
- go.sum
- rpm/rpm_test.go
- testdata/acceptance/keys/test.rpm.repo
- testdata/acceptance/rpm.signed.dockerfile
I have been able to reproduce issue #265 in the acceptance tests. I will work on a fix.
> Fix RPM Verify signature: BAD PARAMETERS when installing from a repo, but not a local file

- .golangci.yml
- README.md
- acceptance_test.go
- apk/apk.go
- apk/apk_test.go
- cmd/nfpm/main.go
- deb/deb.go
- deb/deb_test.go
- files/files.go
- files/files_test.go
- go.mod
- internal/sign/pgp.go
- internal/sign/pgp_test.go
- nfpm.go
- nfpm_test.go
- rpm/rpm.go
- rpm/rpm_test.go
- www/docs/usage.md
following #267, version as v2 now.
BREAKING CHANGE: changes import path to add a /v2 sufffix
> feat: version as v2

- nfpm.go
- nfpm_test.go
removed more deprecated things...
my plan is to roll it in v2.1 (because I forgot about it in v2.0)
> feat: more deprecated things to remove

- go.mod
- go.sum
> feat: update deps

- .goreleaser.yml
- Dockerfile
- remove unneeded rpm package from it
- push to ghcr as well
- added labels
- multi-platform images
- arm64 builds
- fix deprecated goreleaser config
> feat: improve docker image

- files/files.go
- files/files_test.go
Honor mode and mtime value set in yaml file.
- Fixes #296
> Don't override mode/mtime file information if already set

- apk/apk_test.go
- deb/deb_test.go
- files/files.go
- go.mod
- go.sum
- internal/glob/glob.go
- internal/glob/glob_test.go
- rpm/rpm_test.go
> feat: upgrade fileglob

- .github/workflows/build.yml
- Makefile
> feat: build matrix

- .github/workflows/build.yml
- Makefile
- www/docs/install.md
run `go mod tidy` instead of `go mod download`.
refs https://github.com/goreleaser/goreleaser/issues/2088
> fix(ci): go mod tidy

- .goreleaser.yml
- cmd/nfpm/main.go
also copy versioning output from goreleaser...
> feat: gomod verifiable builds

- nfpm.go
> fix: remove semver parsing code before schema version detection

- .gitattributes
- go.mod
- go.sum
- internal/cmd/root.go
- internal/cmd/schema.go
- nfpm.go
- scripts/cmd_docs.sh
- www/docs/cmd/nfpm.md
- www/docs/cmd/nfpm_jsonschema.md
- www/docs/configuration.md
- www/docs/static/schema.json
- adds a new `jsonschema` subcommand that generates the jsonschema for `nfpm.yml`
- adds some annotations to our structs so the schema is generated somewhat properly
- adds related docs
> feat: jsonschema

- Taskfile.yml
> Fix build task.

- apk/apk.go
- deb/deb.go
- rpm/rpm.go
also added a todo
will try to figure out the arch names on the others too
> refactor: improve if a bit

- apk/apk.go
- apk/apk_test.go
- deb/deb_test.go
- rpm/rpm.go
- rpm/rpm_test.go
added more arches, improved test coverage a bit
> fix: added more arches

- .github/ISSUE_TEMPLATE.md
- .github/workflows/build.yml
- .github/workflows/docs.yml
- .github/workflows/generate.yml
- .github/workflows/lint.yml
- .github/workflows/lock.yml
- CONTRIBUTING.md
- README.md
- www/docs/contributing.md
- www/docs/usage.md
- www/mkdocs.yml
same as https://github.com/goreleaser/goreleaser/issues/2645
impact seem low to me, wdyt?
> feat: rename branch to main

- .github/workflows/build.yml
otherwise dependabot will keep pinging us every time
> chore(ci): use major cache action version

- deb/deb.go
refs https://github.com/goreleaser/goreleaser/issues/2721
> fix: deb on arm5 and arm6

- go.mod
- go.sum
- internal/cmd/docs.go
- internal/cmd/init.go
- internal/cmd/man.go
- internal/cmd/package.go
- internal/cmd/root.go
- internal/cmd/schema.go
cobra does not require that great amount of deps anymore
> feat(deps): switch back to cobra

- www/docs/overrides/partials/integrations/analytics.html
- www/mkdocs.yml
> docs: remove analytics

- .github/workflows/build.yml
- .github/workflows/docs.yml
- .github/workflows/generate.yml
- .github/workflows/lint.yml
- .golangci.yml
- CONTRIBUTING.md
- go.mod
- go.sum
> feat: use go 1.18

- .goreleaser.yml
https://fishshell.com/docs/current/completions.html#where-to-put-completions
> fix: fish completions path on nfpm

- apk/apk_test.go
- arch/arch.go
- arch/arch_test.go
- deb/deb_test.go
- internal/cmd/package.go
- rpm/rpm_test.go
> fix: archlinux globs

- www/docs/configuration.md
Changes eg to e.g. and other slightly less trivial ones. Thanks
> fixes minor typos

- Taskfile.yml
- scripts/vercel/build.sh
- scripts/vercel/install.sh
- vercel.json
merge after 48h to ensure DNS is propagated.
before merging, delete site on vercel.com
refs https://github.com/goreleaser/goreleaser/issues/3502
> docs: remove vercel deploy

- nfpm.go
closes: https://github.com/goreleaser/nfpm/issues/589
> Fix expansion of env vars in non-overriden package relation fields

- deb/deb.go
- deb/deb_test.go
- testdata/acceptance/deb.dockerfile
> fix(deb): changelog fixes

- apk/apk_test.go
- arch/arch_test.go
- deb/deb_test.go
- nfpm_test.go
- rpm/rpm_test.go
use `t.TempDir` and `t.Setenv`
> test: improve test code

- deb/deb.go
- deb/deb_test.go
- deb/testdata/bad_provides.golden
> fix(deb): do not allow empty items in deb.provides

- .github/workflows/build.yml
- .github/workflows/generate.yml
- .github/workflows/lint.yml
- .github/workflows/release.yml
> feat: upgrade go

- .golangci.yml
- apk/apk.go
- apk/apk_test.go
- arch/arch.go
- arch/arch_test.go
- deb/deb.go
- files/files.go
- internal/cmd/root.go
- internal/sign/pgp.go
- internal/sign/pgp_test.go
- nfpm_test.go
- rpm/rpm.go
pretty much merged with goreleaser's and fixed all issues
> refactor: stricter golangci-lint ruleset

- www/docs/install.md
- www/mkdocs.yml
> docs: fix verify instructions

- internal/cmd/docs.go
- internal/cmd/init.go
- internal/cmd/man.go
- internal/cmd/package.go
- internal/cmd/root.go
- internal/cmd/schema.go
See individual commits for details.
> feat: completion improvements

- cmd/nfpm/main.go
`nfpm version nfpm version <version>` -> `nfpm version <version>`
> fix: version output

- .github/workflows/build.yml
WIP automating building the package on windows and installing on linux, to make sure paths are all ok.
> build: pkg on windows, install on linux

- acceptance_test.go
- testdata/acceptance/deb.dockerfile
- testdata/acceptance/deb.predepends.yaml
> test: deb.predepends integration test

- apk/apk.go
- apk/apk_test.go
closes #724 
https://wiki.alpinelinux.org/wiki/Package_policies
> fix(apk): alpine conventional file name

- files/files.go
- files/files_test.go
> fix: use parent owner/group on typedir

- arch/arch.go
- deb/deb.go
- internal/modtime/mtime.go
- nfpm.go
- rpm/rpm.go
> fix: modtime

- deb/deb.go
- deb/deb_test.go
- deb/testdata/bad_provides.golden
- deb/testdata/control.golden
> feat(deb): set license field

- rpm/rpm.go
- rpm/rpm_test.go
- testdata/acceptance/deb.dockerfile
- testdata/acceptance/rpm.dockerfile
this adds a `src.rpm` packager.
refs https://github.com/goreleaser/goreleaser/pull/3412
> feat: srpm

- files/files.go
- files/files_test.go
- nfpm.go
- rpm/rpm_test.go
> fix: symlink with empty mtime
