- .travis.yml
- cmd/nfpm/nfpm.yaml.example
- deb/deb.go
- deb/deb_test.go
- deb/testdata/control.golden
- nfpm.go
- rpm/rpm.go
- rpm/rpm_test.go
- rpm/testdata/spec.golden
- rpm/testdata/spec_4.12.x.golden
- rpm/testdata/spec_4.13.x.golden
- rpm/testdata/spec_4.14.x.golden
closes #2
relevant docs: 
- http://rpm.org/user_doc/boolean_dependencies.html
- http://rpm.org/user_doc/dependencies.html
> feat: support recommending and suggesting packages

- Makefile
- deb/deb.go
- deb/deb_test.go
closes #6 
tl;dr: the problem was in the `data.tar.gz`, which had only the files, but not the folders themselves.
I had to walk through the desired path and create the headers inside the tar file, which fixes the issue as it seems.
```
drwxr-xr-x  0 0      0           0 Dec 31  1969 usr/
drwxr-xr-x  0 0      0           0 Dec 31  1969 usr/bin/
-rwxr-xr-x  0 0      0     1034959 Feb 25 14:58 usr/bin/rclone
drwxr-xr-x  0 0      0           0 Dec 31  1969 usr/
drwxr-xr-x  0 0      0           0 Dec 31  1969 usr/share/
drwxr-xr-x  0 0      0           0 Dec 31  1969 usr/share/doc/
drwxr-xr-x  0 0      0           0 Dec 31  1969 usr/share/doc/rclone/
-rw-r--r--  0 0      0        3267 Feb 25 14:58 usr/share/doc/rclone/README.txt
drwxr-xr-x  0 0      0           0 Dec 31  1969 usr/
drwxr-xr-x …
```
> fix: deb: create subfolders and use GNU tar format

- nfpm.go
- nfpm_test.go
I've just hit an issue where `dpkg` was failing to process the Debian control file generated by `nfpm`. 
```
dpkg: error processing archive /var/cache/apt/archives/testpackage_0.0.1_amd64.deb (--unpack):
parsing file '/var/lib/dpkg/tmp.ci/control' near line 9 package 'testpackage':
end of file before value of field 'Description' (missing final newline)
Errors were encountered while processing:
/var/cache/apt/archives/testpackage_0.0.1_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
```
This behavior can be reproduced by not providing a Description value, which according to the [official specs](https://www.debian.org/doc/debian-policy/#the-description-of-a-package), every Debian package must have one.
Of course this can be worked around by actually giving a description, …
> Provide default value for Description field

- deb/deb.go
To be able to build arm6 and arm7 packages, added required
architectures to the goarchToDebian mapping.
> add: Add arm6 and arm7 support to deb package

- cmd/nfpm/main.go
I noticed that the new feature of pre- und postinstall scripts isn't
reflected in the output of the example config file. This commit adds the
missing parts to make it clearer that this feature is available.
See #19
> docs: Add overrides section to example config

- deb/deb.go
- deb/deb_test.go
- deb/testdata/minimal.golden
The Debian policy[1] declares the following control file fields as
required for binary packages:
* Package
* Version
* Section
* Priority
* Architecture
* Maintainer
* Description
All other fields are optional. A few programs handling .deb packages
emit warnings when optional fields exist without a value.
With this change the template generating the control file is updated to
omit empty values. Comments are added to denote mandatory fields.
A newly added test verifies the generated control file.
[1]
<https://www.debian.org/doc/debian-policy/ch-controlfields.html#binary-package-control-files-debian-control>
> deb: Avoid emitting empty fields

- rpm/rpm.go
- rpm/rpm_test.go
Updated nfpm to perform a mapping to appropriate architectures for the
POWER big and little endian architectures.
Note that I also made some changes to unrelated tests to make the linter happy.
> feat: rpm compatible arch for ppc64/ppc64le

- rpm/rpm.go
RPM.Package() populates a temp directory with files to do its work. It should cleanup after itself.
> rpm: Cleanup temp files

- deb/deb.go
- deb/deb_test.go
- deb/testdata/withepoch.golden
- nfpm.go
- rpm/rpm.go
- rpm/testdata/spec_4.12.x.golden
- rpm/testdata/spec_4.13.x.golden
- rpm/testdata/spec_4.14.x.golden
> Added Packager and Epoch tags

- .travis.yml
- acceptance/acceptance_test.go
- acceptance/testdata/deb.arm64.dockerfile
- acceptance/testdata/rpm.arm64.dockerfile
- acceptance/testdata/simple.arm64.yaml
- rpm/rpm.go
- rpm/rpm_test.go
Signed-off-by: Christoph Hartmann <chris@lollyrock.com>
Rhel/Fedora use `aarch64` instead of `arm64`.
Reference:
- https://fedoraproject.org/wiki/Architectures/ARM#Introduction
> add support for build rpm packages for aarch64

- nfpm.go
- rpm/rpm.go
- rpm/rpm_test.go
- rpm/testdata/spec_4.15.x.golden
Prefix and Group tags added for RPMs only since those tags do not exist for deb packages. 
Also defined some macros for rpmbuild to make nfpm less dependent on the build environment.
> Adding Prefix and Group tags

- acceptance/acceptance_test.go
- acceptance/testdata/gzip.compression.yaml
- acceptance/testdata/gzip.rpm.compression.dockerfile
- acceptance/testdata/lzma.compression.yaml
- acceptance/testdata/lzma.rpm.compression.dockerfile
- acceptance/testdata/xz.compression.yaml
- acceptance/testdata/xz.rpm.compression.dockerfile
- nfpm.go
- rpm/rpm.go
Allows you to choose between gzip, xz, and lzma as the RPM compression type.
See #62
> feat: Add option for RPM compression type

- nfpm.go
- rpm/rpm.go
- rpm/rpm_test.go
[2nd attempt, didn't realize there was a test suite issue in rpm that needed to be addressed]
Add support for a setting a 'Release' value other than '1'
```
$ head -5 nfpm.yaml 
name: "csync"
arch: "amd64"
platform: "linux"
version: "1.0.1"
section: "Applications/System"
$ nfpm pkg --target foo.rpm && rpm -qip foo.rpm | head -4 && rm foo.rpm
using rpm packager...
created package: foo.rpm
Name        : csync
Version     : 1.0.1
Release     : 1
Architecture: x86_64
$ ed nfpm.yaml
650
/version
version: "1.0.1"
a
release: "2"
.
wq
663
$ head -5 nfpm.yaml 
name: "csync"
arch: "amd64"
platform: "linux"
version: "1.0.1"
release: "2"
$ nfpm pkg --target foo.rpm && rpm -qip foo.rpm | head -4 && rm foo.rpm
using rpm packager...
created package: foo.rpm
Name        : csync
Version     : 1.0.1 …
```
> feat: add release field

- rpm/rpm.go
Fixes a small typo in source comments.
> fix: Typo in rpm.go comments

- Makefile
- acceptance/acceptance_test.go
- acceptance/testdata/deb.env-var-version.dockerfile
- acceptance/testdata/env-var-version.yaml
- acceptance/testdata/rpm.env-var-version.dockerfile
- acceptance/testdata/simple.yaml
- deb/deb.go
- go.mod
- go.sum
- nfpm.go
- rpm/rpm.go
* Split the parsed version into `Version` & `Release`
* Properly build the deb `Version` using `~` to seperate `Version` & `Release`
* No longer have a custom version parser for rpm
Closes: #50
> fix: parse the version as a semver

- .githooks/pre-commit
- .gitignore
- .golangci.yml
- Makefile
- acceptance/placeholder.go
- cmd/nfpm/main.go
- deb/deb.go
- deb/deb_test.go
- glob/glob.go
- nfpm.go
- nfpm_test.go
- rpm/rpm.go
- rpm/rpm_test.go
These are the errors that were found and fixed
```
./bin/golangci-lint run --exclude-use-default=false --fix -v
INFO [config_reader] Config search paths: [./ /opt/projects/go/nfpm /opt/projects/go /opt/projects /opt /] 
INFO [config_reader] Used config file .golangci.yml 
INFO [lintersdb] Active 36 linters: [bodyclose deadcode depguard dogsled dupl errcheck funlen gochecknoglobals gochecknoinits gocognit goconst gocritic gocyclo gofmt goimports golint gosec gosimple govet ineffassign interfacer lll maligned misspell nakedret prealloc scopelint staticcheck structcheck stylecheck typecheck unconvert unparam unused varcheck whitespace] 
INFO [loader] Go packages loading at mode 575 (deps|exports_file|files|types_sizes|compiled_files|name|imports) took 339.823287ms 
INFO …
```
> chore: add stricter linting

- rpm/rpm.go
- rpm/rpm_test.go
refs https://github.com/goreleaser/goreleaser/issues/1213
> fix: empty release on rpm

- acceptance/testdata/release.rpm.yaml
- nfpm.go
- rpm/rpm_test.go
As far as I understand `Prefix` is just to avoid repeating a folder when referencing files.
so, it seems like it didn't make much sense before, and makes less sense now.
IMHO we can just remove it.
`Release` is already a field on the `root` struct, so I think we can remove it as well.
> fix: remove rpm.Prefix and rpm.Release

- cmd/nfpm/main.go
just fixing a small typo that stuck out to me as I set this up!
> fix: Correct typo in eaxmple config

- .DEREK.yml
Derek can be used on any number of repos without maintaining
separate sets of files or rules - just with a redirect setting as
per this commit. Merge if that's interesting to the project lead
Also - see the new features for Derek in the USER_GUIDE.md
https://github.com/alexellis/derek/blob/master/USER_GUIDE.md
> Create redirect for Derek

- cmd/nfpm/main.go
- go.sum
- nfpm.go
- nfpm_test.go
- rpm/rpm.go
- rpm/rpm_test.go
refs https://github.com/goreleaser/goreleaser/issues/1229#issuecomment-549659537
~~not sure this is the right way to go, I'm sleepy and will check again tomorrow :)~~
fixed in a more proper way, moved the version parse to `WithDefaults`.
> fix(rpm): with defaults: fix version and pre-release

- CONTRIBUTING.md
- acceptance/acceptance_test.go
- cmd/nfpm/main.go
- deb/deb.go
- nfpm.go
- rpm/rpm.go
ensure the package is not included in itself when using globs to match all files
Closes #103
> fix(#103): ensure the package is not included in itself 

- deb/deb.go
- rpm/rpm.go
refs https://github.com/goreleaser/goreleaser/issues/1256
goreleaser do not set target, which causes the bug there.
> fix: suffix check

- deb/deb.go
I updated your ARM architecture as ARM6 is actually armhf and ARM5 is armel (I think) as per this page: https://github.com/golang/go/wiki/GoArm
> fix: updated architectures for arm5 and arm6

- go.mod
- go.sum
- rpm/rpm.go
- rpm/rpm_test.go
Epoch is already merged in google/rpmpack (https://github.com/google/rpmpack/commit/aa36bfddb3a0c725e19c73e75d76fea48882c399)
> fix: make epoch work again

- acceptance/testdata/rpm.min.dockerfile
- rpm/rpm.go
> fix: ensure rpm files have owner

- deb/deb.go
- deb/deb_test.go
- deb/testdata/multiline.golden
Hi There
The description field in the DEB control file supports multiline/verbatim input. It is done by indenting the lines by two spaces. Before this patch, the control file was broken if a user wanted to supply a multiline description.
Blank lines by using a full-stop-character are not implemented as it requires to convert the whole block to a 1-level intended block instead of the verbatim 2-level intended block.
Ref: [debian-policy](https://www.debian.org/doc/debian-policy/ch-controlfields.html#description)
> fix: Handle multiline input for the Debian description field

- glob/glob.go
- glob/glob_test.go
We use nfpm for creating Debian packages. In our nfpm.yaml file we make use of glob patterns for `files`. In the following example we copy all artifacts from `a` to `/tmp/a` and from `b` to `/tmp/b`:
```
files:
"./a/**/*": "/tmp/a/"
"./b/**/*": "/tmp/b/"
```
nfpm does not work as expected when the directories `a` or `b` only contain a single file (e.g. ./a/test.txt). In this case nfpm creates a deb package that contains the content of ./a/test.txt as a file at the path /tmp/a. Instead we expect ./a/test.txt to be packaged as file at the path /tmp/a/test.txt.
For our use cases this fix is kind of important and the only work-around right now is to make sure that there are always at least two files below a and b.
> Fix glob patterns for files and config_files

- acceptance/testdata/complex.yaml
- acceptance/testdata/rpm.complex.dockerfile
- rpm/rpm.go
Fixes goreleaser/goreleaser/issues/1636
`recommends` was not being included in the rpmpack struct so including that field in the nfpm config was ineffective. fixed that so that rpms correctly include the recommended packages.
After applying this patch and rebuilding goreleaser:
```
$ sudo dnf repoquery --recommends ./my-app.rpm
Last metadata expiration check: 2:10:04 ago on Wed 01 Jul 2020 10:28:08 AM EDT.
< the recommended dependency >
$ sudo dnf install ./my-app.rpm               
Last metadata expiration check: 2:10:11 ago on Wed 01 Jul 2020 10:28:08 AM EDT.
Dependencies resolved.
===
[...]
Installing weak dependencies:
< the recommended dependency >
```
> fix rpm recommends

- rpm/rpm.go
If I'm not mistaken, there is currently no way to build architecture independent DEB and RPM packages with the same configuration file. This change enables users to do this by specifying `arch: all` by translating `all` to `noarch` for RPMs, which is the equivalent architecture there.
PS: I couldn't locally run the the CI pipeline because I created this pull request on a machine without access to docker, but it should be okay for such a minor change.
> Feature(RPM): Allow platform independet packages by translating arch "all" to "noarch" for RPM packages

- cmd/nfpm/main.go
- deb/deb.go
- nfpm.go
- nfpm_test.go
- rpm/rpm.go
This pull request changes the behaviour of the `--target` CLI option to produce conventional file for the respective packages by default. Conventional file names are for example [package_version_architecture.package-type](https://manpages.debian.org/buster/dpkg-dev/dpkg-name.1.en.html) for Debian packages and [name-version-release.architecture.rpm](http://ftp.rpm.org/max-rpm/ch-rpm-file-format.html) for RPMs. Consider the following cases:
* **`--target` is blank or omitted:** Create a package with a conventional file name in current directory
* **`--target` is a directory:** Create a package with a conventional file name in the directory
* **`--target` is a file name:** Use this file name
Because at the moment, `nfpm` allows users to omit `--target` and uses the very weird default …
> WIP: feat: Use conventional file names by default

- rpm/rpm.go
I accidentally used the wrong separator for RPM files in #157. I'm sorry I missed this earlier.
> fix: Fix wrong separator in conventional RPM file name.

- CONTRIBUTING.md
- www/docs/install.md
we don't really test on go 1.11, so better don't assume it works.
changed docs to instruct the usage of latest version
also upgraded other deprecated instructions.
closes https://github.com/goreleaser/nfpm/issues/127
> docs: update contributing.md

- acceptance/testdata/rpm.changelog.dockerfile
- deb/deb.go
- deb/deb_test.go
- rpm/rpm.go
This pull request fixes the following formatting problems in changelogs:
* RPM: Unintended changenote indentation after first note
* DEB: Remove unnecessary leading and trailing newlines
Also, the acceptance test are now more strict when checking the RPM changelog formatting.
> fix: Improve changelog formatting.

- deb/deb.go
- deb/deb_test.go
- rpm/rpm.go
- rpm/rpm_test.go
This pull request adds release and pre-release information to the conventional file names. I did not include this earlier because I thought that `info.Version` already contained the full version information available. This results in the following possibilities:
* `1.2.3` if `info.Release` and `info.Prerelease` are empty
* `1.2.3-4` if `info.Release` is set to `4` and `info.Prerelease` is empty
* `1.2.3-4~5` if `info.Release` is set to `4` and `info.Prerelease` is set to `5
* `1.2.3~5` if `info.Release` is empty and `info.Prerelease` is set to `5`
This only affects the default output file names.
> fix: Reflect (pre)release in conventional file names.

- deb/deb_test.go
- rpm/rpm_test.go
I tried to fix #132, where the build failed for configurations in which files are referenced via symlinks in macOS. So first I wrote some tests for both `rpm` and `deb` packages to reproduce the issue. However, on my MacBook running Catalina, the packages built perfectly fine and symlinks were followed, so I did not change anything in the packaging process.
I figured, more tests are never bad so this pull request contains the tests with symlinks. If I missed something and the issue does indeed exist, these tests are also still a great starting point for further debugging. Also the tests introduce a handy helper function to extract files from `rpm`s and they also fix a minor issue with the helper function to extract files from `.tar.gz` archives.
> test(#132): Add tests with symlinked files.

- acceptance/acceptance_test.go
- acceptance/testdata/deb.triggers.dockerfile
- acceptance/testdata/scripts/postinstall_trigger.sh
- acceptance/testdata/triggers.yaml
- deb/deb.go
- deb/deb_test.go
- nfpm.go
- www/docs/configuration.md
This pull request adds support for triggers in .deb files. These triggers are commonly used for tasks like rebuilding man pages or `initramfs`. Packages can activate a trigger for other packages or claim interest on triggers activated by other packages. For further information see https://wiki.debian.org/DpkgTriggers, https://man7.org/linux/man-pages/man5/deb-triggers.5.html.
In addition to the feature support, this pull request adds **unit tests**, an **acceptance test** and **documentation**. However, the following changes probably need some feedback before merging:
* The trigger names internally use a `-` (e.g. `activate-noawait`), however I used a `_` (e.g. `activate_noawait`)for the `nfpm` configuration to adhere to yaml conventions.
* `createControl` is now 2 or 3 lines above the …
> feat: Add support for DEB triggers.

- acceptance/acceptance_test.go
- acceptance/testdata/deb.symlink.dockerfile
- acceptance/testdata/rpm.symlink.dockerfile
- acceptance/testdata/symlink.yaml
- cmd/nfpm/main.go
- deb/deb.go
- deb/deb_test.go
- nfpm.go
- rpm/rpm.go
- rpm/rpm_test.go
- www/docs/configuration.md
This pull request is an alternative approach to #184 for adding symlinks, as described in my comments in issue #183 (closes #183). In this approach, symlinks can be added as follows:
```
symlinks:
/path/to/symlink: /path/to/target
```
This approach will not break existing build configurations and supports both package formats. The API is consistent with `config_files` and `empty_folders` and does not promote symlinks in `files` which are broken on the build host that will only eventually work in the context of the package root. Also the changes to the `nfpm.go`, `deb.go` and `rpm.go` are very minimal. Also the separate configuration option makes it clear that symlinks `files:` are followed because otherwise there would be no need for a separate option.
If we want to develop this approach, …
> feat(#183): Support symlinks for deb and rpm.

- acceptance/testdata/deb.env-var-version.dockerfile
- nfpm.go
- nfpm_test.go
- www/docs/configuration.md
This pull request closes #130 by not propagating the semver metadata info the `Deb.Metadata` field. As described in the corresponding issue, this is the expected behaviour for `deb` files.
EDIT: changed it to wip because I actually don't even know why `Deb.Metadata` exists if it shouldn't be included in the version.
> fix(#130): Don't propagate semver metadata into deb metadata.

- rpm/rpm_test.go
This pull request replace the tag constant definitions in the rpm tests with the constants that were already provided by `rpmutils`. I think that makes sense because they are always used in conjunction with `rpm.Header.GetString` which is also a `rpmutils` function. As I see it `rpmutils` is meant to be used this way.
> test: Reuse rpm tag constants from rpmutils.

- cmd/nfpm/main.go
In #157 I accidentally introduced a bug that results in a panic if `--target` is a directory or blank. This pull request fixes this by printing a useful error message instead. 
A minor issue: The `doPackage()` line limit enforced by `golangci-lint:funlen` is exceeded by 4 lines which in my opinion is acceptable, so i added `// nolint:funlen`.
> fix: Avoid panic if target is blank/dir and no packager is specified.

- rpm/rpm.go
- rpm/rpm_test.go
- www/docs/configuration.md
This pull request removes the default RPM group tag value, adds documentation and tests for both a blank and a populated group tag. Closes #193.
Also making sure that there is always an new pull request 😆
> fix: Remove RPM group default.

- acceptance/acceptance_test.go
stream logs, should make it easier to understand what's going on.
> ci: make acceptance test logs more readable

- deb/deb.go
- deb/deb_test.go
In earlier pull requests, I accidentally added symlink and changelog files to the `deb` `.tar.gz` files with a leading `/`. This pull requests removes these leading `/`s such that no warning is displayed by `tar` anymore when unpacking. I also added a tests that assures that no files included in the data and control `.tar.gz` starts with `/`.
> fix: Remove leading slashes from files in .tag.gz files in deb.

- www/docs/configuration.md
This PR adds docs with examples for `depends` `overrides`:
* Version constraints with different notations between formats (as discussed in #200)
* Packages that are named differently between distros
> docs: Give overrides examples for depends with version constraints.

- acceptance/testdata/rpm.env-var-version.dockerfile
- nfpm.go
- nfpm_test.go
- rpm/rpm.go
- rpm/rpm_test.go
This pull request fixes (hopefully) the version, release and prerelease handling for RPMs. Also, globally for all package formats, a semver prerelease present in `info.Version` will not populate `info.Release` anymore since `info.Version` should contain version information of the packaged subject and not the package itself.
Closes #131. Maybe we should also wait for feedback from @boogie-byte before merging.
> fix: Correctly handle version, release and prerelease for RPMs.

- acceptance/testdata/apk.env-var-version.dockerfile
- acceptance/testdata/deb.env-var-version.dockerfile
- acceptance/testdata/rpm.env-var-version.dockerfile
- apk/apk.go
- deb/deb.go
- deb/deb_test.go
- nfpm.go
- rpm/rpm.go
- rpm/rpm_test.go
- www/docs/configuration.md
I added the global config field `VersionMetadata` for all packagers. I chose `version_metadata` for the YAML field because metadata is such a generic term that most people won't associate it with the version otherwise. The `deb` packager already supported this and the `apk` formatter borrowed it from the `deb`-specific option which was not ideal.
`Deb.VersionMetadata` is now deprecated an a warning will be emitted to stderr if it is still set (same for `BinDir`).
If not explicitly set, the `VersionMetadata` can be populated from `Version` semver metadata.
Also the tests and conventional file names are updated.
> feat: Introduce version_metadata for all packagers (deprecate deb.metadata)

- acceptance/testdata/deb.changelog.dockerfile
- deb/deb.go
- deb/deb_test.go
This pull request is based on #217 and ensures that files inside `.tar.gz` files of `deb` packages adhere to the same path prefix convention as regular upstream Debian packages. I created this PR to fix the broken acceptance test in #217 which was caused by the fact that `dpkg` in Ubuntu Docker images is configured to ignore changelog files but ONLY if we adhere to the path prefix conventions that are introduced in the PR.
During debugging I also found a nasty bug when generating the `md5sums` file if a changelog is added that results in a broken `md5sums` file. I included the fix and corresponding test in this PR because the changes were all lumped together after I was done debugging. Sorry for the mess.
> Fix: Fix deb file path prefixes and md5sums file

- acceptance/testdata/deb.changelog.dockerfile
Change `apt upgrade` to `apt update` before installing a package. This was a typo and now this test should also run faster.
> fix: Change upgrade to update in changelog dockerfile

- go.mod
- go.sum
https://github.com/google/rpmpack/pull/39 was just merged, so we can use the upstream `rpmpack` again.
> Deps: Use upstream rpmpack.

- apk/apk.go
- apk/apk_test.go
- deb/deb.go
- deb/deb_test.go
- go.mod
- internal/glob/glob.go
- internal/glob/glob_test.go
- internal/sign/pgp.go
- internal/sign/rsa.go
- nfpm.go
- rpm/rpm.go
- rpm/rpm_test.go
replace usages of `errors.Wrap` with `fmt.Errorf` using the new `%w` thing.
> refactor: remove pkg/errors

- acceptance/testdata/rpm.meta.dockerfile
- go.mod
- go.sum
- internal/glob/glob_test.go
This PR updates `go-zglob` to the first commit that supports escaping. This allows `nfpm` to package files that contain special glob characters such as `{` and `}`.
> deps: Update zglob.

- deb/deb.go
- deb/deb_test.go
- deb/testdata/templates.golden
- nfpm.go
- www/docs/configuration.md
Add support for `templates` file inside `DEBIAN` that is needed for `debconf` to be able to ask question user during installation. More on subject [here](http://www.fifi.org/doc/debconf-doc/tutorial.html) and [here](https://manpages.debian.org/testing/debconf-doc/debconf-devel.7.en.html)
> feat: add support for deb templates

- nfpm.go
- rpm/rpm.go
- rpm/rpm_test.go
- www/docs/configuration.md
The previous behaviour was to use only the first line of the
description as the summary. In some cases, it is desirable to have a
separate summary. Since only RPM packages have a summary field, I've
put this inside the RPM configuration.
description: This is my description
rpm:
summary: This is my summary
By default, just use the first line of the description.
> feat: Allow explicit summary from RPM packages

- acceptance/testdata/complex.386.yaml
- acceptance/testdata/complex.yaml
- acceptance/testdata/overrides.yaml
- apk/apk_test.go
- deb/deb_test.go
- go.mod
- go.sum
- internal/files/files_test.go
- internal/glob/glob.go
- internal/glob/glob_test.go
- rpm/rpm_test.go
BREAKING CHANGE: may have unintended side-effects.
closes #232
error message when no files match a glog changed, because now its handled in another place... but seems like tests are still passing...
> feat: replace glob library

- nfpm.go
- rpm/rpm.go
- rpm/rpm_test.go
- www/docs/configuration.md
From the [Maximum RPM] guide:
The %ghost Directive
As we mentioned in the Section called The %files List, if a file
is specified in the %files list, that file will automatically be
included in the package. There are times when a file should be
owned by the package but not installed - log files and state files
are good examples of cases you might desire this to happen.
The way to achieve this, is to use the %ghost directive. By adding
this directive to the line containing a file, RPM will know about
the ghosted file, but will not add it to the package.
Ghost files are specified using `Type: rpmpack.GhostFile` when
constructing the output package.
The test ensures that we have:
- The target file present in the RPM.
- The specified mode attributes (although not really important,
either).
- …
> feat: Support RPM ghost files

- go.mod
- go.sum
- rpm/rpm_test.go
Bump github.com/google/rpmpack to integrate the ghost file handling
fix [google/rpmpack 52].
Updated the TestRPMGhostFiles fix to test the updated
functionality. Now, we expect that the files are listed in the RPM
header, but without any cpio content.
This is an extension of PR #246.
[google/rpmpack 52]: https://github.com/google/rpmpack/pull/52
> test: Intergate and test rpmpack ghost file fix

- files/files.go
- files/files_test.go
- nfpm.go
- testdata/contents.yaml
- www/docs/configuration.md
remove unused custom yaml parse and make some code a bit clearer...
> fix: race condition and remove unused code

- nfpm.go
- nfpm_test.go
- testdata/env-fields.yaml
- www/docs/configuration.md
I want to use the same config file for local builds that are not signed and pipeline builds that are signed so I need to be able to specify the key_file as an env var.
> fix: allow using an env var in the signature.key_file field

- testdata/acceptance/apk.386.complex.dockerfile
- testdata/acceptance/apk.386.dockerfile
- testdata/acceptance/apk.arm64.dockerfile
- testdata/acceptance/apk.changelog.dockerfile
- testdata/acceptance/apk.complex.dockerfile
- testdata/acceptance/apk.dockerfile
- testdata/acceptance/apk.env-var-version.dockerfile
- testdata/acceptance/apk.meta.dockerfile
- testdata/acceptance/apk.min.dockerfile
- testdata/acceptance/apk.overrides.dockerfile
- testdata/acceptance/apk.ppc64le.dockerfile
- testdata/acceptance/apk.signed.dockerfile
- testdata/acceptance/apk.symlink.dockerfile
I will create another issue to track the requirement that we start embedding the checksums in the apk files.
> fix: set the alpine linux version to v3.12 so the acceptance tests pass

- files/files.go
- files/files_test.go
- go.sum
- www/docs/configuration.md
This PR makes `ExpandContentGlobs` return an error when multiple contents share the same destination. Otherwise, the destination would just be overwritten.
This leads to particularly nasty broken packages when the symlink convention is misunderstood, so I improved the documentation for that too. If you think that doesn't belong in this PR I will split the PR. But first hear me out:
Everyone I know (including myself) always forgets the order of arguments in `ln -s file1 file2` such that most of the time `ln` calls are preceded by `man ln`. So refering to `ln` in the `nfpm` docs for symlinks might not be the best idea. I learned this the hard way when I added a symlink to a package thinking that
```
- src: /usr/bin/mybinary
dst: /path/to/my/actual/binary
type: symlink
```
means that I …
> fix: Prevent destination collisions

- apk/apk.go
- apk/apk_test.go
- go.sum
- looking at official packages, seems like only SHA1 is needed (made a small thing to check that: https://github.com/caarlos0/apkcat)
- added tests
- fixed the missing write to the hasher function
The packages actually had the file contents as a header as well as far as I understand. 
PS: tested it with goreleaser itself as well.
Refs https://github.com/goreleaser/nfpm/commit/3b7e01508a19a2fa6e2ebb1b4685dd4e3cbfd785
refs #291
> fix: apk checksums

- files/files.go
- files/files_test.go
This PR fixes #302 by taking per-file packagers into account when detecting file destination collisions.
> fix: Fix file collision detection with per-file packagers

- deb/deb.go
- nfpm.go
- testdata/acceptance/rules.deb.yaml
- testdata/acceptance/scripts/config
- testdata/acceptance/scripts/templates
- www/docs/configuration.md
With debconf, the config script is responsible for asking any questions necessary to configure a package [1]. Without this, we're forced to ask questions in postinst, which is against best practices:
> Avoid asking questions in the postinst. Instead, the config script should ask questions using debconf, so that pre-configuration will work.
This adds the possibility to include a config script when using debconf like so:
```yaml
deb:
scripts:
templates: ./my/templates
config: ./my/config
```
[1] https://manpages.debian.org/jessie/debconf-doc/debconf-devel.7.en.html
> feat: Support for deb's config maintenance script

- nfpm.go
- nfpm_test.go
- www/docs/configuration.md
> feat: add version_schema config option to allow controlling how the version string is parsed.

- www/docs/install.md
To install with Go, the instructions need the path suffixed with `/cmd/nfpm`
Go 1.16 will bark if you don't have `@latest` on that in addition
```console
$ go install github.com/goreleaser/nfpm       
go install: version is required when current directory is not in a module
Try 'go install github.com/goreleaser/nfpm@latest' to install the latest version
```
```console
$ go install github.com/goreleaser/nfpm@latest
go: downloading github.com/goreleaser/nfpm v1.10.3
go: downloading github.com/Masterminds/goutils v1.1.0
go: downloading github.com/mitchellh/copystructure v1.0.0
go: downloading golang.org/x/crypto v0.0.0-20201208171446-5f87f3452ae9
go: downloading golang.org/x/net v0.0.0-20201209123823-ac852fbbde11
go install: package github.com/goreleaser/nfpm is not a main package
``` …
> docs: fix `go install` instructions

- acceptance_test.go
- deb/deb.go
- deb/deb_test.go
- nfpm.go
- testdata/acceptance/deb.dockerfile
- testdata/acceptance/deb.gzip.compression.yaml
- testdata/acceptance/deb.none.compression.yaml
- testdata/acceptance/deb.xz.compression.yaml
- www/docs/configuration.md
This PR adds a `compression` option for `deb` files. Currently the following values are supported:
* `gzip` (default)
* `xz` (future default)
* `none` (no compression)
I think the best way to move forward is to keep `gzip` as default for now and wait for feedback from the users that use `xz`. If everything works great (and if `xz` build times are acceptable), we should make `xz` the default in a following release.
Closes #361.
> feat: compression option with xz support for deb

- README.md
'software' is not a 'countable' kind of noun which attracts pluralization.  It's like 'traffic' or 'mail', which are the same kind of noun and also do not normally get pluralized as nouns.
> docs: fix typo on README.md

- apk/apk.go
- apk/apk_test.go
- deb/deb.go
- nfpm.go
- rpm/rpm.go
- www/docs/configuration.md
This PR fixes #367 by allowing platform specific arch overrides. The documentation now also clarifies that the `arch` field is translated and references the override options.
I also removed `arch` defaulting to `amd64` for APKs as it was not consistent with the other packagers and it should be specified in any case in order to avoid invalid packages (`amd64` packages without `amd64` specific contents or with an `arm` binary).
> Feature: Allow platform specific arch overrides.

- apk/apk.go
- deb/deb.go
- testdata/acceptance/apk.dockerfile
- testdata/acceptance/core.complex.yaml
- testdata/acceptance/deb.dockerfile
- testdata/acceptance/rpm.dockerfile
- www/docs/configuration.md
This PRs fixes #392 by passing the full file mode instead of just the permissions (which is the mode masked with `0o777`) to the `tar` header. It also added acceptance tests with suid bit for all packagers and documentation that reminds users to specify the mode in octal.
> Fix: Allow complex file modes for debs and apks.

- www/docs/install.md
Hi
1. looks like the $PWD should be bind mounted as `/tmp`, otherwise the `/tmp` won't be visible on the host system
2. I set the container workdir to `tmp` so that the relative paths in foo.yml can be resolved
> fix docker exec example

- files/files.go
- internal/cmd/package.go
- nfpm.go
- nfpm_test.go
This PR fixes #387 and #393 by reducing the algorithmic complexity of the content destination collision detection. Previously when appending an element, the destination was compared to all other elements in the content list. Now we simply append and check for collisions once at the end with a single pass through all elements.
For 150000 files with random destinations, the performance compares as follows:
```
Before: BenchmarkExpandContentGlobs-4   	       1	2982879539110 ns/op
Now   : BenchmarkExpandContentGlobs-4   	       1	9052880061 ns/op
```
**That's a 320x improvement from 50 minutes to 9 seconds for extreme use cases!**
Here's the benchmark code:
```Go
func BenchmarkExpandContentGlobs(b *testing.B) {
contents := testContents(150000)
b.ResetTimer()
for i := 0; i < b.N; i++ {
_, err …
```
> Fix: Improve performance of content destination collision detection.

- acceptance_test.go
- apk/apk.go
- apk/apk_test.go
- deb/deb.go
- deb/deb_test.go
- files/files.go
- nfpm.go
- rpm/rpm.go
- rpm/rpm_test.go
- testdata/acceptance/rpm.directories.yaml
- testdata/acceptance/rpm.dockerfile
- www/docs/configuration.md
This PR introduces the content type `dir` which can be used to add empty directories or directories with custom attributes such as owner, group or permissions. It also makes `EmptyFolders` obsolete.
Another important aspect is that it can be used to specified directories "owned" by the package when packaging RPMs as only those directories are removed when the package is uninstalled. This use case is also now well documented.
> feat: Directory content type with custom attributes

- deb/deb.go
- deprecation/deprecation.go
- deprecation/deprecation_test.go
- nfpm.go
as discussed in another issue
this would allow, for example, goreleaser, to set its own deprecation notice "provider" to nfpm...
> feat: add deprecation notice interface

- nfpm.go
- nfpm_test.go
- www/docs/configuration.md
This PR allows to expand env for vendor field. This can be useful if another entity wants to redistribute a package.
> feat: expand-env support for vendor field

- nfpm.go
- nfpm_test.go
- rpm/rpm.go
- rpm/rpm_test.go
- www/docs/configuration.md
Atm rpm `Packager` uses the maintainer value which is sometimes not true when another entity wants to redistribute a package:
> ```
> #
> # Example spec file for cdplayer app...
> #
> Summary: A CD player app that rocks!
> Name: cdplayer
> Version: 1.0
> Release: 1
> License: GPL
> Group: Applications/Sound
> Source: ftp://ftp.gnomovision.com/pub/cdplayer/cdplayer-1.0.tgz
> URL: http://www.gnomovision.com/cdplayer/cdplayer.html
> Distribution: WSS Linux
> Vendor: White Socks Software, Inc.
> Packager: Santa Claus <sclaus@northpole.com>
> 
> %description
> It slices!  It dices!  It's a CD player app that
> can't be beat.  By using the resonant frequency
> of the CD itself, it is able to simulate 20X
> oversampling.  This leads to sound quality that
> cannot be equaled with more mundane …
```
> feat: custom packager configuration for rpm pkg

- apk/apk.go
- apk/apk_test.go
- deb/deb.go
- deb/deb_test.go
- files/files.go
Currently a package can contain duplicate folders depending on the way a user specified a dir-type content destination (folder name). This PR fixes that by keeping track of created folders in the already existing `created` map with a **consistent naming convention**. It also adds related tests.
Another bug that's also fixed by this PR is that auto-created folders did not have a owner username and group name.
> fix: Prevent duplicate folders from being created.

- files/files.go
- files/files_test.go
- internal/glob/glob.go
- internal/glob/glob_test.go
This PR fixes a bug where file sources containing matchers result in the files being created inside folders of the same name as the file when globbing is disabled.
**Example:**
```
src: foo/{bar}/config.json
dst: /etc/config.json
```
resulted in this:
```
src: foo/{bar}/config.json
dst: /etc/config.json/config.json
```
when it should have actually just remain unchanged.
> fix: Fix destinations for files containing matchers when globbing is disabled.

- acceptance_test.go
shouldn't have merged https://github.com/goreleaser/nfpm/pull/412
problem is when you request debian linux/arm/6, the arm7 image is given...
```sh
docker run --platform linux/arm/6 --rm  debian uname -a
```
it was working before because our test was wrong (arch was arm7 and testing against a arm7, thinking it was arm6)
> fix: disable debian arm6 tests

- Taskfile.yml
version v0.2.0 has removed the -s flag.
It is now always on.
https://github.com/mvdan/gofumpt/releases/tag/v0.2.0
fixes  #420
> chore(Taskfile): Remove -s flag for gofumpt

- apk/apk.go
- apk/apk_test.go
- deb/deb.go
- deb/deb_test.go
- rpm/rpm_test.go
- testdata/acceptance/apk.dockerfile
- testdata/acceptance/core.complex.yaml
- testdata/acceptance/deb.dockerfile
- testdata/acceptance/rpm.dockerfile
refs https://github.com/goreleaser/goreleaser/issues/2792
> fix: create tree of dir content types

- deb/deb.go
- deb/testdata/multiline.golden
refs https://github.com/goreleaser/goreleaser/issues/2861
> fix: deb multilines should have 1 space prefix

- deb/deb.go
- deb/testdata/control.golden
- deb/testdata/control2.golden
refs #439 
lintian says:
```
W: nfpm: unknown-field nfpm_amd64.deb Vendor
```
> fix: vendor is not a recognized deb control field

- nfpm.go
- nfpm_test.go
Now the version is expanded in version, but in case, when many packages are built and depend on near one with the same version it doesn't work.
> Expand dependencies' version

- go.mod
- go.sum
- nfpm.go
- rpm/rpm.go
- rpm/rpm_test.go
The default compression level for rpm is 9. https://github.com/google/rpmpack/blob/master/rpm.go#L165
Because of it, rpm packaging is significantly slower than deb, almost 5 times worse.
Here I bump the dependencies, add tests and change default level to -1
> fix: update rpmpack and change default compressor to gzip:-1 (a default level) instead of gzip:9

- apk/apk.go
- deb/deb.go
- go.mod
- go.sum
Here's the difference between compress/gzip and https://github.com/klauspost/pgzip binary on 16 cores laptop
```
Feb 12 19:15:42 + nfpm package --target /output --config clickhouse-common-static.yaml --packager deb
Feb 12 19:15:42 using deb packager...
Feb 12 19:17:15 created package: /output/clickhouse-common-static_22.2.1.1638_amd64.deb
93 seconds
Feb 12 19:34:00 + ./nfpm package --target /output --config clickhouse-common-static.yaml --packager deb
Feb 12 19:34:00 using deb packager...
Feb 12 19:34:13 created package: /output/clickhouse-common-static_22.2.1.1638_amd64.deb
13 seconds
```
The resulting deb package is 1015M.
I am leaving a standard `compress/gzip` in tests to have a reference.
> feat: replace compress/gzip by klauspost/pgzip

- deb/deb.go
- deb/deb_test.go
- deb/testdata/control4.golden
This should have been caught in https://github.com/goreleaser/nfpm/pull/375 but I missed it.
The version string when using `Release` is correct in the filename, but incorrect in the control file.
Here's the [debian docs on the control file's version](https://www.debian.org/doc/debian-policy/ch-controlfields.html#version)
Before:
Filename: `foo_1.2.3~pre+meta-2_amd64.deb`
control version: `1.2.3-2~pre+meta`
After:
Filename: `foo_1.2.3~pre+meta-2_amd64.deb`
control version: `1.2.3~pre+meta-2`
✅ `task ci` 🚀
> fix: deb version order in control

- internal/cmd/package.go
Found a duplication within the --help page of package command. Just pitching in a slight polish :ok_hand:
> Fix typo on 'package' commands --help

- deb/deb.go
- deb/deb_test.go
- internal/sign/pgp.go
- nfpm.go
As mentioned [here](https://github.com/goreleaser/nfpm/issues/212) Debsign package verification is a PITA.
Herewith my proposal to implement dpkg-sig style package verification.
As mentioned in the original thread, debsign and dpkg-sig are mutually exclusive, but it would be nice to be able to choose between them.
> feat: implement dpkg-sig Package signing

- nfpm.go
- nfpm_test.go
- testdata/acceptance/core.complex.yaml
- testdata/acceptance/core.env-var-version.yaml
- testdata/acceptance/upgrade.v1.yaml
- testdata/acceptance/upgrade.v2.yaml
- www/docs/static/schema.json
deprecated for a long time now, let's remove it!
> feat: remove empty_folders for good

- .github/workflows/build.yml
- deprecation/deprecation_test.go
- scripts/test.sh
> chore(ci): improve tparse

- files/files.go
- nfpm.go
- www/docs/static/schema.json
the jsonschema lib was updated, and now only supports json tags...
this duplicates the json and yaml tags, which is horrible and I'm happy to hear if there's a better way...
https://github.com/invopop/jsonschema/pull/23
> fix: json schema

- .github/workflows/build.yml
- .github/workflows/lint.yml
- apk/apk.go
- deb/deb.go
- internal/glob/glob.go
- nfpm.go
- nfpm_test.go
- added govulnscan
- added semgrep
- added ruleguard
- improved some matrix configs
- using setup-go's cache option directly
> fix: govulncheck, semgrep & ruleguard scan/fixes

- www/docs/tips.md
Fixes: https://github.com/goreleaser/nfpm/issues/501
Fix post-remove example in docs. Based on https://github.com/goreleaser/nfpm/blob/main/testdata/acceptance/scripts/postremove.sh
> Fix post-remove script example

- .github/workflows/build.yml
- .github/workflows/codeql.yml
- .github/workflows/docs.yml
- .github/workflows/generate.yml
- .github/workflows/lint.yml
- .github/workflows/lock.yml
- .github/workflows/milestone.yml
- .github/workflows/release.yml
- split release into another workflow - we only release after some time anyway, so tests already passed on main, no need to wait for them again
- minor improvements et al on the other workflows as well
- forcing go >=1.19.1
> chore: improving ci config

- nfpm.go
> feat: allow to parse from stdin

- files/files_test.go
- internal/glob/glob.go
- internal/glob/glob_test.go
> fix: relative paths to dirs

- arch/arch.go
- arch/arch_test.go
> fix: archlinux prerelease

- www/docs/configuration.md
Using a `v` prefix for the `version` field happens to work if the version is semver-compatible, since the semver parser will strip the `v`. If it is not semver-compatible, then a `v` prefix should not be used, since some package managers (like deb) won't accept it.
> docs: Discourage "v" prefix for version numbers

- apk/apk_test.go
- arch/arch_test.go
- deb/deb_test.go
- internal/cmd/init.go
- internal/rpmpack/rpm_test.go
- rpm/rpm_test.go
- testdata/acceptance/apk.dockerfile
- testdata/acceptance/archlinux.dockerfile
- testdata/acceptance/core.complex.yaml
- testdata/acceptance/core.env-var-version.yaml
- testdata/acceptance/core.min.yaml
- testdata/acceptance/core.overrides.yaml
- testdata/acceptance/core.signed.yaml
- testdata/acceptance/core.simple.yaml
- testdata/acceptance/core.withchangelog.yaml
- testdata/acceptance/deb.debsign.sign.yaml
- testdata/acceptance/deb.dockerfile
- testdata/acceptance/deb.dpkg-sig.sign.yaml
- testdata/acceptance/deb.gzip.compression.yaml
- testdata/acceptance/deb.none.compression.yaml
- testdata/acceptance/deb.rules.yaml
- testdata/acceptance/deb.triggers.yaml
- testdata/acceptance/deb.xz.compression.yaml
- testdata/acceptance/rpm.dockerfile
- testdata/acceptance/rpm.gzip.compression.yaml
- testdata/acceptance/rpm.lzma.compression.yaml
- testdata/acceptance/rpm.release.yaml
- testdata/acceptance/rpm.xz.compression.yaml
- www/docs/configuration.md
Examples, tests and docs often refer to /usr/local/bin, which should only be used for things compiled locally, which is not the case of installed packages.
Changed that to /usr/bin, and also some usages of things like /usr/something to /usr/share/something.
> fix: do not encourage using /usr/local/bin

- apk/apk.go
- apk/apk_test.go
- arch/arch.go
- arch/arch_test.go
- deb/deb.go
- deb/deb_test.go
- nfpm.go
- nfpm_test.go
- rpm/rpm_test.go
- www/docs/configuration.md
Surprising that GOARCH was expanded, but GOOS was not.
More consistent to expand both of them the same way ?
Implement platform for deb packager, goes into Architecture.    
Validate that the platform is "linux", for Alpine and Arch.
Closes #600
> feat: expand variables in platform field

- acceptance_test.go
- deb/deb.go
- deb/deb_test.go
- testdata/acceptance/deb.dockerfile
- testdata/acceptance/deb.zstd.compression.yaml
- testdata/acceptance/rpm.zstd.compression.yaml
- www/docs/configuration.md
This PR adds `zstd` compression support for `deb` and `rpm`. For `deb`, an exception for the acceptance tests was needed as `zstd` is not yet supported in the debian base image. Due to `rpmpack`, `zstd` was already supported for `rpms` and we already tested it in our `rpm` tests but it was not documented, yet.
> feat: add zstd compression support for deb and rpm

- go.mod
- internal/rpmpack/header.go
- internal/rpmpack/rpm.go
- nfpm_test.go
wrap pgp errors with `fmt.Errorf` so we can use `errors.Is`, and `require.ErrorIs`
> feat: wrap pgp errors

- arch/arch.go
- arch/arch_test.go
this walks up the destination and creates the `.MTREE` entries for the parents too, otherwise packages are not installable by `pacman`.
if anyone knows a better way to do this, I'm all ears... 
closes https://github.com/goreleaser/nfpm/issues/638
> fix(archlinux): .MTREE should have parent dirs as well

- deb/deb.go
- testdata/acceptance/core.withchangelog.yaml
- testdata/acceptance/deb.dockerfile
- testdata/changelog.yaml
- testdata/copyright
- Missing trailing ./ in md5sums for changelog.Debian.gz caused md5sums-lists-nonexistent-file and file-missing-in-md5sums and is fixed using files.AsExplicitRelativePath.
- Adding copyright file fixes no-copyright-file.
- Set file_info fixes executable-is-not-world-readable, non-standard-executable-perm, non-standard-file-perm.
- Adding section fixes unknown-section, empty-field.
- Using standard compress/gzip module fixes package-contains-timestamped-gzip, because klauspost/pgzip does not support empty mod time.
- Adding urgency and distribution in changelog fixes syntax-error-in-debian-changelog.
- Adding mail address to maintainer fixes malformed-contact.
- Correcting description fixes description-starts-with-package-name and description-starts-with-leading-spaces.
> fix: md5sums entries and lintian errors/warnings

- .golangci.yml
golangci-lint 1.53 upgrades depguard to v2, and per [their words](https://twitter.com/golangci/status/1664374779808284677),
> ⚠️WARNING⚠️
> depguard configuration has completely changed
> fix(golangci-lint): depguard (v2) config for >= 1.53

- nfpm.go
- nfpm_test.go
- www/docs/configuration.md
This is convenient in CI, one real world example usage in tests and docs.
(FWIW, `CI_REPOSITORY_URL` is a predefined env var at least in GitLab CI.)
> feat: expand environment variables in deb fields values

- .goreleaser.yml
- https://github.com/goreleaser/nfpm/discussions/673
I checked GitHub Actions log, then it seems there is an space between `nfpm_` and `2.30.0`.
https://github.com/goreleaser/nfpm/actions/runs/5180574010/jobs/9334922406
```
• archives
• creating                                       archive=dist/nfpm_ 2.30.0_Windows_arm64.zip
• creating                                       archive=dist/nfpm_ 2.30.0_Windows_x86_64.zip
• creating                                       archive=dist/nfpm_ 2.30.0_Linux_arm64.tar.gz
• creating                                       archive=dist/nfpm_ 2.30.0_Linux_x86_[64](https://github.com/goreleaser/nfpm/actions/runs/5180574010/jobs/9334922406#step:13:65).tar.gz
• creating                                       archive=dist/nfpm_ 2.30.0_Darwin_x86_64.tar.gz
• …
```
> chore: remove space from asset name

- .gitignore
- acceptance_test.go
- testdata/acceptance/rpm_centos7.dockerfile
- testdata/acceptance/rpm_centos8.dockerfile
- testdata/acceptance/rpm_centos9.dockerfile
I wanted to see how far back nfpm still works... seems like centos 8 is the last one.
Now, on a subsequent PR, I'll try to upgrade openpgp lib... I'm fairly certain at least centos8 will break.
We can then decide next steps.
> test: signatures on centos 7 and 8

- nfpm.go
- rpm/rpm.go
- rpm/rpm_test.go
- testdata/acceptance/core.complex.yaml
- testdata/acceptance/rpm.dockerfile
- www/docs/configuration.md
> feat(rpm): support relocatable packages

- apk/apk.go
- arch/arch.go
- deb/deb.go
- files/files.go
- files/files_test.go
- internal/glob/glob.go
- internal/glob/glob_test.go
- rpm/rpm.go
fixed all backslash issues that I/the CI found
refs https://github.com/goreleaser/goreleaser/issues/4174
> fix: windows

- nfpm.go
- nfpm_test.go
- www/docs/configuration.md
For example, GitLab CI has `CI_PROJECT_URL` which can be useful here.
> feat: expand env variables in homepage field

- nfpm_test.go
- www/docs/configuration.md
`$CI_REPOSITORY_URL` is not quite appropriate for `Vcs-Git`, use `$CI_PROJECT_URL` with `Vcs-Browser` instead.
- https://docs.gitlab.com/ee/ci/variables/predefined_variables.html
- https://www.debian.org/doc/debian-policy/ch-controlfields.html#version-control-system-vcs-fields
> docs: improve deb fields var expansion example

- apk/apk.go
- apk/apk_test.go
- deb/deb.go
- deb/deb_test.go
- nfpm.go
- rpm/rpm.go
- rpm/rpm_test.go
When used as a library, `nfpm.PackageSignature.SignFn` can be set as an alternative to `KeyFile`. This allows arbitrary signing key implementations, like a remote signing server.
Updates https://github.com/tailscale/tailscale/issues/1882
> feat: Add support for remote signing keys

- deb/deb.go
- deb/deb_test.go
- deb/testdata/bad_provides.golden
- deb/testdata/control.golden
- nfpm.go
- www/docs/configuration.md
Basic support for adding 'Pre-Depends:' to Debian packages added.
> feat: add minimal support for Debian pre-dependencies

- rpm/rpm.go
- rpm/rpm_test.go
- testdata/acceptance/rpm.dockerfile
> fix(rpm): conventional file name should always have the release

- rpm/rpm.go
- rpm/rpm_test.go
- testdata/acceptance/rpm.dockerfile
formatVersion is also used to set the version field of the RPM, which should not contain the release.
this fixes it, and the tests which were wrong.
closes #714
> fix(rpm): conventionalfilename

- www/docs/goarch-to-pkg.md
The docs had an extra `v` in the GOARCH+GOARM values.
Drop the `v` to match the actual translation tables:
https://github.com/goreleaser/nfpm/blob/6c241370ccdd5718730556f2b8c13e4733d0fda7/apk/apk.go#L65-L66 https://github.com/goreleaser/nfpm/blob/6c241370ccdd5718730556f2b8c13e4733d0fda7/arch/arch.go#L46-L48 https://github.com/goreleaser/nfpm/blob/6c241370ccdd5718730556f2b8c13e4733d0fda7/deb/deb.go#L40-L42 https://github.com/goreleaser/nfpm/blob/6c241370ccdd5718730556f2b8c13e4733d0fda7/rpm/rpm.go#L63-L65
> Correct GOARCH docs

- deb/deb.go
- deb/deb_test.go
- deb/testdata/multiline.golden
Blank lines in the deb's control file description are valid but need to be encoded with a space followed by a dot (`.`).
See https://www.debian.org/doc/debian-policy/ch-controlfields.html#s-f-description.
> Those containing a single space followed by a single full stop character. These are rendered as blank lines. This is the only way to get a blank line.
I used nfpm to package one of my apps and it was broken as it did not add the dots onto the blank lines. This PR fixes that.
> fix(deb): blank line in package description

- deb/deb.go
Each time building exaclty from the same source,
ensure exaclty the same size deb package is generated.
> fix: Ensure reproducable Deb package

- files/files.go
- files/files_test.go
If set, SOURCE_DATE_EPOCH will be honored for all content entries.
> fix: Honor SOURCE_DATE_EPOCH for files

- files/files.go
- files/files_test.go
> fix: file mode when type: tree

- acceptance_test.go
- nfpm.go
- rpm/rpm.go
- rpm/rpm_test.go
- testdata/acceptance/core.complex.yaml
- testdata/acceptance/rpm.dockerfile
- testdata/acceptance/rpm.verify.yaml
- testdata/acceptance/scripts/verify.sh
- testdata/scripts/verify.sh
- www/docs/configuration.md
- www/docs/static/schema.json
RPM allows users to add custom verify scriptlets that are run by `rpm -V` in addition to the normal checksum validation. This is useful when there are additional factors that indicate a valid installation, like, for example, checking for valid contents of configuration files.
> feat(rpm): add support for verify scriptlet

- apk/apk.go
- apk/apk_test.go
- apk/testdata/TestControl.golden
- apk/testdata/TestCreateBuilderControl.golden
- apk/testdata/TestCreateBuilderControlScripts.golden
> fix(apk): conventional name template

- .goreleaser.yml
> add s390x support

- apk/apk.go
- apk/apk_test.go
> fix(apk): always append .rsa.pub to key name

- go.mod
- go.sum
- rpm/rpm.go
- rpm/rpm_test.go
> feat(rpm): properly handle optional fields

- files/files.go
- files/files_test.go
- files/fs.go
forcefully set dirs owned by the FS as implicit dirs.
the rpm implementation should then not add them, which should be the right behavior I think.
this way these files will still be owned by the `filesystem` package instead of the package being built.
this only affects `type: tree`.
also added logrotate to the list of "common" paths.
closes #829
> fix: better handle files owned by the fs

- rpm/rpm.go
- rpm/rpm_test.go
> fix: rpm doesnt allow dashes in prerelease

- deb/deb.go
- deb/deb_test.go
- internal/sign/pgp.go
Closes #840
Applying hex-encoding to MD5 and SHA1 hashes in dpkg-sig signing method, adding newlines between single file lines.
Verifying digests in dpkg-sig unit testing
> fix(deb): dpkg-sig format

- nfpm.go
- nfpm_test.go
- testdata/env-fields.yaml
- www/docs/configuration.md
Hello!
I noticed you support the environment variable interpolation in many fields in a configuration but not in the description.
This merge request fills this gap.
I added the unit tests for the new code and altered the docs. Please notify me if I missed something or if my code doesn't fit your coding guidelines - I will fix it.
Regards!
> feat: env var substitution in description

- flake.nix
This commit fixes the undefined staging-pkgs like in the GitHub Actions runs:
[example](https://github.com/goreleaser/nfpm/actions/runs/10854480085/job/30124997498#step:4:87)
> fix: undefined variable 'staging-pkgs'

- apk/apk_test.go
- arch/arch.go
- deb/deb.go
- deb/deb_test.go
- files/files.go
- ipk/ipk.go
- ipk/ipk_test.go
- rpm/rpm.go
- rpm/rpm_test.go
- www/docs/configuration.md
> feat(rpm): support %config(missingok)

- .golangci.yml
- files/files.go
- rpm/rpm_test.go
This fixes [failing pipeline](https://github.com/goreleaser/nfpm/actions/runs/11904635646/job/33173773343).
> fix: testifylint and revive lint issues

- .goreleaser.yml
- adds a source package
- adds the AUR from sources
Based on the current [PKGBUILD](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=nfpm)
> ci: publish AUR from sources

- .goreleaser.yml
The source archive doesn't have a sub-directory.
> fix: aur sources archive content

- deb/deb.go
- files/files.go
This PR fixes the file/dir modes in the `.deb` data tar headers. When creating directory entries based on actual on-disk directories, their modes ended up including some flags that confused graphical package manager frontends (`Software Install` and `gdebi`). With this PR, the mode field in the tar header only contains the permissions, because other type information is already included in other header fields.
Fixes #856.
> fix(deb): content file modes to support gdebi

- nfpm.go
- rpm/rpm.go
- rpm/rpm_test.go
- www/docs/configuration.md
- www/docs/static/schema.json
This commit adds the BuildHost option to the RPM specific configurations. If the build host is not provided it will default to os.Hostname() which is the previous behavior. This allows reproduce-able builds when the build environment spans multiple hosts.
> feat: Add BuildHost option to RPM packages

- www/docs/goarch-to-pkg.md
The actual code seems to leave GOARCH="amd64" as "amd64" for deb packages:
https://github.com/goreleaser/nfpm/blob/8e999742a1ba06e2a68bd461e39b16eef8e4c669/deb/deb.go#L42-L52
(If I am correct that being absent from that map means that a string will be used without changes.)
However, the documentation currently claims that it will be mapped to "x86_64".
Just to be clear, I believe that the code [is correct](https://www.debian.org/ports/#portlist-released). The value  "x86_64", as used in the documentation, is correct for rpm but not for deb. This PR aims to change the documentation to match the code.
> Corrected amd64 name for deb in goarch-to-pkg.md

- www/docs/tips.md
On my Raspberry Pi, the first line of `systemctl --version` looks like this :
```
systemd 252 (252.36-1~deb12u1)
```
The `systemd_version` variable should be an integer because it is compared to 231 a couple of line further.
In the proposed change, I use `grep` instead of `sed`. The `grep` command prints all integers from the line, and the second `head -1` keeps the first integer only.
> Improve version extraction of `systemctl`
